-- Curated attractions catalog used by the native Android app.
-- The catalog is read-only for clients; user selections are still saved in
-- the existing trips.payload.sights JSON section.

create table if not exists public.sight_catalog (
    id text primary key,
    city_key text not null,
    city_name_ru text not null,
    city_name_en text not null,
    city_name_es text not null default '',
    city_name_de text not null default '',
    name_ru text not null,
    name_en text not null,
    name_es text not null default '',
    name_de text not null default '',
    description_ru text not null default '',
    description_en text not null default '',
    description_es text not null default '',
    description_de text not null default '',
    category text not null default 'достопримечательности',
    latitude double precision,
    longitude double precision,
    map_url text not null default '',
    search_text text not null default '',
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

alter table public.sight_catalog enable row level security;

revoke all on table public.sight_catalog from public, anon, authenticated;
grant select on table public.sight_catalog to authenticated;

drop policy if exists sight_catalog_read_authenticated on public.sight_catalog;
create policy sight_catalog_read_authenticated
    on public.sight_catalog
    for select
    to authenticated
    using (true);

create index if not exists sight_catalog_city_key_idx on public.sight_catalog (city_key);
create index if not exists sight_catalog_city_ru_idx on public.sight_catalog (city_name_ru);
create index if not exists sight_catalog_city_en_idx on public.sight_catalog (city_name_en);
create index if not exists sight_catalog_city_es_idx on public.sight_catalog (city_name_es);
create index if not exists sight_catalog_city_de_idx on public.sight_catalog (city_name_de);

insert into public.sight_catalog (
    id, city_key, city_name_ru, city_name_en, city_name_es, city_name_de,
    name_ru, name_en, name_es, name_de,
    description_ru, description_en, description_es, description_de,
    category, latitude, longitude, map_url, search_text, sort_order
) values
    ('prague-castle', 'prague', 'Прага', 'Prague', 'Praga', 'Prag', 'Пражский град', 'Prague Castle', 'Castillo de Praga', 'Prager Burg', 'Исторический комплекс с собором Святого Вита и панорамой города.', 'Historic complex with St. Vitus Cathedral and city views.', 'Complejo histórico con la catedral de San Vito y vistas de la ciudad.', 'Historischer Komplex mit Veitsdom und Blick über die Stadt.', 'достопримечательности', 50.0910, 14.4016, 'https://www.google.com/maps/search/?api=1&query=50.0910,14.4016', 'hrad|castle|castillo|burg', 10),
    ('charles-bridge', 'prague', 'Прага', 'Prague', 'Praga', 'Prag', 'Карлов мост', 'Charles Bridge', 'Puente de Carlos', 'Karlsbrücke', 'Средневековый мост через Влтаву с видами на Старый город.', 'Medieval bridge over the Vltava with views of the Old Town.', 'Puente medieval sobre el Moldava con vistas al casco antiguo.', 'Mittelalterliche Brücke über die Moldau mit Blick auf die Altstadt.', 'достопримечательности', 50.0865, 14.4114, 'https://www.google.com/maps/search/?api=1&query=50.0865,14.4114', 'karluv most|bridge|puente|brücke', 20),
    ('old-town-square-prague', 'prague', 'Прага', 'Prague', 'Praga', 'Prag', 'Староместская площадь', 'Old Town Square', 'Plaza de la Ciudad Vieja', 'Altstädter Ring', 'Главная площадь Праги с Астрономическими часами и Тынским храмом.', 'Prague''s main square with the Astronomical Clock and Týn Church.', 'Plaza principal de Praga con el Reloj Astronómico y la iglesia de Týn.', 'Prager Hauptplatz mit astronomischer Uhr und Teynkirche.', 'достопримечательности', 50.0870, 14.4208, 'https://www.google.com/maps/search/?api=1&query=50.0870,14.4208', 'staromak|old town|casco antiguo|altstadt', 30),
    ('st-vitus-cathedral', 'prague', 'Прага', 'Prague', 'Praga', 'Prag', 'Собор Святого Вита', 'St. Vitus Cathedral', 'Catedral de San Vito', 'Veitsdom', 'Главный храм Пражского града с витражами и коронационными реликвиями.', 'The main church of Prague Castle, known for its stained glass and royal history.', 'Templo principal del Castillo de Praga, famoso por sus vidrieras e historia real.', 'Hauptkirche der Prager Burg mit Glasfenstern und königlicher Geschichte.', 'достопримечательности', 50.0909, 14.4005, 'https://www.google.com/maps/search/?api=1&query=50.0909,14.4005', 'katedrala|cathedral|catedral|dom', 40),
    ('wenceslas-square', 'prague', 'Прага', 'Prague', 'Praga', 'Prag', 'Вацлавская площадь', 'Wenceslas Square', 'Plaza de Wenceslao', 'Wenzelsplatz', 'Большой городской бульвар с Национальным музеем и магазинами.', 'Large city boulevard with the National Museum and shops.', 'Gran bulevar urbano con el Museo Nacional y tiendas.', 'Großer Boulevard mit Nationalmuseum und Geschäften.', 'достопримечательности', 50.0810, 14.4280, 'https://www.google.com/maps/search/?api=1&query=50.0810,14.4280', 'vaclavak|wenceslas|wenceslao|wenzel', 50),

    ('zwinger-dresden', 'dresden', 'Дрезден', 'Dresden', 'Dresde', 'Dresden', 'Цвингер', 'Zwinger Palace', 'Palacio Zwinger', 'Zwinger', 'Барочный дворцовый ансамбль с музеями и внутренним садом.', 'Baroque palace complex with museums and an inner courtyard.', 'Complejo palaciego barroco con museos y patio interior.', 'Barockes Palais mit Museen und Innenhof.', 'достопримечательности', 51.0537, 13.7339, 'https://www.google.com/maps/search/?api=1&query=51.0537,13.7339', 'zwinger|palace|palacio|palais', 10),
    ('frauenkirche-dresden', 'dresden', 'Дрезден', 'Dresden', 'Dresde', 'Dresden', 'Фрауэнкирхе', 'Frauenkirche Dresden', 'Iglesia de Nuestra Señora', 'Frauenkirche', 'Лютеранская церковь и один из главных символов восстановленного Дрездена.', 'Lutheran church and one of the symbols of rebuilt Dresden.', 'Iglesia luterana y uno de los símbolos de Dresde reconstruida.', 'Lutherische Kirche und eines der Wahrzeichen des wiederaufgebauten Dresden.', 'достопримечательности', 51.0519, 13.7412, 'https://www.google.com/maps/search/?api=1&query=51.0519,13.7412', 'frauen|church|iglesia|kirche', 20),
    ('semperoper-dresden', 'dresden', 'Дрезден', 'Dresden', 'Dresde', 'Dresden', 'Земперопер', 'Semperoper', 'Ópera Semper', 'Semperoper', 'Знаменитый оперный театр на Театральной площади.', 'Famous opera house on Theaterplatz.', 'Famosa ópera en Theaterplatz.', 'Berühmtes Opernhaus am Theaterplatz.', 'достопримечательности', 51.0545, 13.7351, 'https://www.google.com/maps/search/?api=1&query=51.0545,13.7351', 'opera|oper|theaterplatz|teatro', 30),
    ('bruhls-terrace', 'dresden', 'Дрезден', 'Dresden', 'Dresde', 'Dresden', 'Терраса Брюля', 'Brühl''s Terrace', 'Terraza de Brühl', 'Brühlsche Terrasse', 'Прогулочная терраса над Эльбой с видом на исторический центр.', 'Riverside promenade above the Elbe with views of the historic centre.', 'Paseo sobre el Elba con vistas al centro histórico.', 'Promenade an der Elbe mit Blick auf die historische Altstadt.', 'достопримечательности', 51.0552, 13.7417, 'https://www.google.com/maps/search/?api=1&query=51.0552,13.7417', 'terrace|elba|elbe|paseo', 40),
    ('dresden-residenzschloss', 'dresden', 'Дрезден', 'Dresden', 'Dresde', 'Dresden', 'Дрезденский замок', 'Dresden Castle', 'Castillo de Dresde', 'Residenzschloss Dresden', 'Бывшая резиденция саксонских курфюрстов с музейными коллекциями.', 'Former residence of the Saxon electors with museum collections.', 'Antigua residencia de los electores sajones con colecciones de museos.', 'Ehemalige Residenz der sächsischen Kurfürsten mit Museumssammlungen.', 'достопримечательности', 51.0526, 13.7371, 'https://www.google.com/maps/search/?api=1&query=51.0526,13.7371', 'residenz|castle|castillo|schloss', 50),

    ('marienplatz-munich', 'munich', 'Мюнхен', 'Munich', 'Múnich', 'München', 'Мариенплац', 'Marienplatz', 'Marienplatz', 'Marienplatz', 'Центральная площадь Мюнхена с Новой ратушей и знаменитыми часами.', 'Munich''s central square with the New Town Hall and its famous clock.', 'Plaza central de Múnich con el Nuevo Ayuntamiento y su famoso reloj.', 'Zentraler Platz mit Neuem Rathaus und berühmtem Glockenspiel.', 'достопримечательности', 48.1374, 11.5755, 'https://www.google.com/maps/search/?api=1&query=48.1374,11.5755', 'marien|town hall|ayuntamiento|rathaus', 10),
    ('nymphenburg-palace', 'munich', 'Мюнхен', 'Munich', 'Múnich', 'München', 'Дворец Нимфенбург', 'Nymphenburg Palace', 'Palacio de Nymphenburg', 'Schloss Nymphenburg', 'Роскошная летняя резиденция баварских правителей с большим парком.', 'Grand summer residence of the Bavarian rulers with an extensive park.', 'Residencia de verano de los gobernantes bávaros con un gran parque.', 'Sommerresidenz der bayerischen Herrscher mit weitläufigem Park.', 'достопримечательности', 48.1584, 11.5032, 'https://www.google.com/maps/search/?api=1&query=48.1584,11.5032', 'nymphenburg|palace|palacio|schloss', 20),
    ('english-garden-munich', 'munich', 'Мюнхен', 'Munich', 'Múnich', 'München', 'Английский сад', 'English Garden', 'Jardín Inglés', 'Englischer Garten', 'Один из крупнейших городских парков Европы с серфингом на Айсбахе.', 'One of Europe''s largest urban parks, famous for surfing on the Eisbach.', 'Uno de los parques urbanos más grandes de Europa, famoso por el surf en el Eisbach.', 'Einer der größten Stadtparks Europas, bekannt für die Eisbachwelle.', 'достопримечательности', 48.1590, 11.6030, 'https://www.google.com/maps/search/?api=1&query=48.1590,11.6030', 'garten|park|jardin|surf', 30),
    ('munich-residence', 'munich', 'Мюнхен', 'Munich', 'Múnich', 'München', 'Мюнхенская резиденция', 'Munich Residence', 'Residencia de Múnich', 'Münchner Residenz', 'Дворцовый комплекс в центре города с залами, сокровищницей и театром.', 'Central palace complex with grand halls, a treasury and a theatre.', 'Complejo palaciego céntrico con salones, tesoro y teatro.', 'Zentrale Residenz mit Prunksälen, Schatzkammer und Theater.', 'достопримечательности', 48.1419, 11.5792, 'https://www.google.com/maps/search/?api=1&query=48.1419,11.5792', 'residenz|residence|palacio|residenz', 40),
    ('deutsches-museum', 'munich', 'Мюнхен', 'Munich', 'Múnich', 'München', 'Немецкий музей', 'Deutsches Museum', 'Museo Alemán', 'Deutsches Museum', 'Большой музей науки и техники на острове Изар.', 'Major science and technology museum on an island in the Isar.', 'Gran museo de ciencia y tecnología en una isla del Isar.', 'Großes Wissenschafts- und Technikmuseum auf einer Isarinsel.', 'достопримечательности', 48.1299, 11.5833, 'https://www.google.com/maps/search/?api=1&query=48.1299,11.5833', 'museum|science|ciencia|technik', 50),

    ('hohensalzburg-fortress', 'salzburg', 'Зальцбург', 'Salzburg', 'Salzburgo', 'Salzburg', 'Крепость Хоэнзальцбург', 'Hohensalzburg Fortress', 'Fortaleza de Hohensalzburg', 'Festung Hohensalzburg', 'Средневековая крепость на холме с панорамным видом на Зальцбург.', 'Medieval fortress on a hill with panoramic views over Salzburg.', 'Fortaleza medieval en una colina con vistas panorámicas de Salzburgo.', 'Mittelalterliche Festung auf einem Hügel mit Panoramablick über Salzburg.', 'достопримечательности', 47.7945, 13.0433, 'https://www.google.com/maps/search/?api=1&query=47.7945,13.0433', 'festung|fortress|fortaleza|burg', 10),
    ('mirabell-palace', 'salzburg', 'Зальцбург', 'Salzburg', 'Salzburgo', 'Salzburg', 'Дворец Мирабель', 'Mirabell Palace', 'Palacio de Mirabell', 'Schloss Mirabell', 'Дворец и сад в центре города, известные своей барочной планировкой.', 'Palace and gardens in the city centre, known for their Baroque design.', 'Palacio y jardines del centro conocidos por su diseño barroco.', 'Palais und Garten im Zentrum mit barocker Gestaltung.', 'достопримечательности', 47.8059, 13.0411, 'https://www.google.com/maps/search/?api=1&query=47.8059,13.0411', 'mirabell|garden|jardin|garten', 20),
    ('mozart-birthplace', 'salzburg', 'Зальцбург', 'Salzburg', 'Salzburgo', 'Salzburg', 'Дом рождения Моцарта', 'Mozart''s Birthplace', 'Casa natal de Mozart', 'Mozarts Geburtshaus', 'Музей в доме на Гетрайдегассе, где родился Вольфганг Амадей Моцарт.', 'Museum in the Getreidegasse house where Wolfgang Amadeus Mozart was born.', 'Museo en la casa de Getreidegasse donde nació Wolfgang Amadeus Mozart.', 'Museum im Haus in der Getreidegasse, in dem Wolfgang Amadeus Mozart geboren wurde.', 'достопримечательности', 47.8002, 13.0434, 'https://www.google.com/maps/search/?api=1&query=47.8002,13.0434', 'mozart|birthplace|nacimiento|geburtshaus', 30),
    ('salzburg-cathedral', 'salzburg', 'Зальцбург', 'Salzburg', 'Salzburgo', 'Salzburg', 'Зальцбургский собор', 'Salzburg Cathedral', 'Catedral de Salzburgo', 'Salzburger Dom', 'Барочный собор на Соборной площади в историческом центре.', 'Baroque cathedral on Cathedral Square in the historic centre.', 'Catedral barroca en la plaza de la catedral del centro histórico.', 'Barocke Kathedrale am Domplatz in der historischen Altstadt.', 'достопримечательности', 47.7985, 13.0467, 'https://www.google.com/maps/search/?api=1&query=47.7985,13.0467', 'dom|cathedral|catedral|kirche', 40),
    ('getreidegasse', 'salzburg', 'Зальцбург', 'Salzburg', 'Salzburgo', 'Salzburg', 'Гетрайдегассе', 'Getreidegasse', 'Getreidegasse', 'Getreidegasse', 'Узкая историческая улица с вывесками, магазинами и домом Моцарта.', 'Historic shopping street with distinctive signs and Mozart''s birthplace.', 'Calle histórica con letreros tradicionales y la casa natal de Mozart.', 'Historische Einkaufsstraße mit Zunftzeichen und Mozarts Geburtshaus.', 'достопримечательности', 47.8008, 13.0407, 'https://www.google.com/maps/search/?api=1&query=47.8008,13.0407', 'street|shopping|calle|straße', 50),

    ('schoenbrunn-palace', 'vienna', 'Вена', 'Vienna', 'Viena', 'Wien', 'Дворец Шёнбрунн', 'Schönbrunn Palace', 'Palacio de Schönbrunn', 'Schloss Schönbrunn', 'Императорская резиденция с парком, садами и панорамной террасой.', 'Imperial residence with gardens, a park and a panoramic terrace.', 'Residencia imperial con jardines, parque y terraza panorámica.', 'Kaiserliche Residenz mit Park, Gärten und Panoramaterrasse.', 'достопримечательности', 48.1845, 16.3122, 'https://www.google.com/maps/search/?api=1&query=48.1845,16.3122', 'schonbrunn|palace|palacio|schloss', 10),
    ('st-stephens-vienna', 'vienna', 'Вена', 'Vienna', 'Viena', 'Wien', 'Собор Святого Стефана', 'St. Stephen''s Cathedral', 'Catedral de San Esteban', 'Stephansdom', 'Главный готический собор Вены в самом центре города.', 'Vienna''s main Gothic cathedral in the heart of the city.', 'Catedral gótica principal de Viena en el centro de la ciudad.', 'Wiens wichtigster gotischer Dom im Herzen der Stadt.', 'достопримечательности', 48.2085, 16.3731, 'https://www.google.com/maps/search/?api=1&query=48.2085,16.3731', 'stephansdom|cathedral|catedral|dom', 20),
    ('hofburg-vienna', 'vienna', 'Вена', 'Vienna', 'Viena', 'Wien', 'Хофбург', 'Hofburg', 'Palacio de Hofburg', 'Hofburg', 'Бывшая императорская резиденция с музеями и парадными площадями.', 'Former imperial residence with museums and ceremonial courtyards.', 'Antigua residencia imperial con museos y patios ceremoniales.', 'Ehemalige Kaiserresidenz mit Museen und Prunkhöfen.', 'достопримечательности', 48.2066, 16.3656, 'https://www.google.com/maps/search/?api=1&query=48.2066,16.3656', 'hofburg|imperial|imperial|kaiser', 30),
    ('belvedere-vienna', 'vienna', 'Вена', 'Vienna', 'Viena', 'Wien', 'Дворец Бельведер', 'Belvedere Palace', 'Palacio Belvedere', 'Schloss Belvedere', 'Барочный дворец и музей с коллекцией Климта.', 'Baroque palace and museum known for its Klimt collection.', 'Palacio y museo barroco conocido por su colección de Klimt.', 'Barockes Schloss und Museum mit Klimt-Sammlung.', 'достопримечательности', 48.1914, 16.3807, 'https://www.google.com/maps/search/?api=1&query=48.1914,16.3807', 'belvedere|museum|museo|museum', 40),
    ('museum-quarter-vienna', 'vienna', 'Вена', 'Vienna', 'Viena', 'Wien', 'Музейный квартал', 'MuseumsQuartier', 'Barrio de los Museos', 'MuseumsQuartier', 'Культурный квартал с музеями, дворами и кафе.', 'Cultural quarter with museums, courtyards and cafés.', 'Barrio cultural con museos, patios y cafés.', 'Kulturviertel mit Museen, Höfen und Cafés.', 'достопримечательности', 48.2036, 16.3584, 'https://www.google.com/maps/search/?api=1&query=48.2036,16.3584', 'mq|museums|museos|kultur', 50),

    ('colosseum-rome', 'rome', 'Рим', 'Rome', 'Roma', 'Rom', 'Колизей', 'Colosseum', 'Coliseo', 'Kolosseum', 'Амфитеатр античного Рима и один из самых узнаваемых памятников Италии.', 'Ancient Roman amphitheatre and one of Italy''s most recognisable landmarks.', 'Anfiteatro de la antigua Roma y uno de los monumentos más conocidos de Italia.', 'Antikes römisches Amphitheater und eines der bekanntesten Wahrzeichen Italiens.', 'достопримечательности', 41.8902, 12.4922, 'https://www.google.com/maps/search/?api=1&query=41.8902,12.4922', 'colosseo|amphitheatre|anfiteatro|amphitheater', 10),
    ('pantheon-rome', 'rome', 'Рим', 'Rome', 'Roma', 'Rom', 'Пантеон', 'Pantheon', 'Panteón', 'Pantheon', 'Античный храм с огромным куполом и знаменитым круглым окном в крыше.', 'Ancient temple with a huge dome and its famous roof opening.', 'Templo antiguo con una gran cúpula y su famoso óculo.', 'Antiker Tempel mit gewaltiger Kuppel und berühmter Dachöffnung.', 'достопримечательности', 41.8986, 12.4769, 'https://www.google.com/maps/search/?api=1&query=41.8986,12.4769', 'pantheon|temple|templo|tempel', 20),
    ('trevi-fountain', 'rome', 'Рим', 'Rome', 'Roma', 'Rom', 'Фонтан Треви', 'Trevi Fountain', 'Fontana di Trevi', 'Trevi-Brunnen', 'Барочный фонтан XVIII века и популярная остановка в центре Рима.', 'Eighteenth-century Baroque fountain and a popular stop in central Rome.', 'Fuente barroca del siglo XVIII y parada popular en el centro de Roma.', 'Barockbrunnen aus dem 18. Jahrhundert im Zentrum Roms.', 'достопримечательности', 41.9009, 12.4833, 'https://www.google.com/maps/search/?api=1&query=41.9009,12.4833', 'trevi|fountain|fuente|brunnen', 30),
    ('roman-forum', 'rome', 'Рим', 'Rome', 'Roma', 'Rom', 'Римский форум', 'Roman Forum', 'Foro Romano', 'Forum Romanum', 'Руины политического и религиозного центра Древнего Рима.', 'Ruins of the political and religious centre of ancient Rome.', 'Ruinas del centro político y religioso de la antigua Roma.', 'Ruinen des politischen und religiösen Zentrums des antiken Rom.', 'достопримечательности', 41.8925, 12.4853, 'https://www.google.com/maps/search/?api=1&query=41.8925,12.4853', 'forum|ruins|ruinas|ruinen', 40),
    ('vatican-museums', 'rome', 'Рим', 'Rome', 'Roma', 'Rom', 'Музеи Ватикана', 'Vatican Museums', 'Museos Vaticanos', 'Vatikanische Museen', 'Музейный комплекс с Сикстинской капеллой и коллекциями искусства.', 'Museum complex with the Sistine Chapel and major art collections.', 'Complejo de museos con la Capilla Sixtina y grandes colecciones de arte.', 'Museen mit Sixtinischer Kapelle und bedeutenden Kunstsammlungen.', 'достопримечательности', 41.9065, 12.4536, 'https://www.google.com/maps/search/?api=1&query=41.9065,12.4536', 'vaticano|museum|museo|vatikan', 50),

    ('st-marks-square', 'venice', 'Венеция', 'Venice', 'Venecia', 'Venedig', 'Площадь Сан-Марко', 'St. Mark''s Square', 'Plaza de San Marcos', 'Markusplatz', 'Главная площадь Венеции рядом с базиликой и Дворцом дожей.', 'Venice''s main square beside the basilica and Doge''s Palace.', 'Plaza principal de Venecia junto a la basílica y el Palacio Ducal.', 'Venedigs Hauptplatz neben Basilika und Dogenpalast.', 'достопримечательности', 45.4342, 12.3387, 'https://www.google.com/maps/search/?api=1&query=45.4342,12.3387', 'san marco|piazza|plaza|platz', 10),
    ('doges-palace', 'venice', 'Венеция', 'Venice', 'Venecia', 'Venedig', 'Дворец дожей', 'Doge''s Palace', 'Palacio Ducal', 'Dogenpalast', 'Готический дворец на набережной Сан-Марко с парадными залами.', 'Gothic palace on the waterfront with grand ceremonial rooms.', 'Palacio gótico junto al agua con grandes salones ceremoniales.', 'Gotischer Palast am Wasser mit prachtvollen Sälen.', 'достопримечательности', 45.4337, 12.3403, 'https://www.google.com/maps/search/?api=1&query=45.4337,12.3403', 'doge|palace|palacio|palast', 20),
    ('rialto-bridge', 'venice', 'Венеция', 'Venice', 'Venecia', 'Venedig', 'Мост Риальто', 'Rialto Bridge', 'Puente de Rialto', 'Rialtobrücke', 'Самый известный мост через Гранд-канал с торговыми рядами.', 'The best-known bridge over the Grand Canal with shops.', 'El puente más famoso sobre el Gran Canal con tiendas.', 'Die bekannteste Brücke über den Canal Grande mit Geschäften.', 'достопримечательности', 45.4380, 12.3359, 'https://www.google.com/maps/search/?api=1&query=45.4380,12.3359', 'rialto|bridge|puente|brücke', 30),
    ('grand-canal-venice', 'venice', 'Венеция', 'Venice', 'Venecia', 'Venedig', 'Гранд-канал', 'Grand Canal', 'Gran Canal', 'Canale Grande', 'Главный водный путь Венеции с дворцами и видами с вапоретто.', 'Venice''s main waterway lined with palaces and vaporetto views.', 'La vía de agua principal de Venecia, rodeada de palacios.', 'Venedigs wichtigste Wasserstraße mit Palästen und Vaporetto-Blick.', 'достопримечательности', 45.4370, 12.3330, 'https://www.google.com/maps/search/?api=1&query=45.4370,12.3330', 'canal|waterway|canale|kanal', 40),
    ('bridge-of-sighs', 'venice', 'Венеция', 'Venice', 'Venecia', 'Venedig', 'Мост Вздохов', 'Bridge of Sighs', 'Puente de los Suspiros', 'Seufzerbrücke', 'Крытый мост между Дворцом дожей и бывшей тюрьмой.', 'Covered bridge connecting Doge''s Palace with the former prison.', 'Puente cubierto que une el Palacio Ducal con la antigua prisión.', 'Überdachte Brücke zwischen Dogenpalast und ehemaligem Gefängnis.', 'достопримечательности', 45.4341, 12.3398, 'https://www.google.com/maps/search/?api=1&query=45.4341,12.3398', 'sighs|bridge|suspiros|seufzer', 50),

    ('florence-duomo', 'florence', 'Флоренция', 'Florence', 'Florencia', 'Florenz', 'Собор Санта-Мария-дель-Фьоре', 'Florence Cathedral', 'Catedral de Florencia', 'Dom von Florenz', 'Знаменитый собор с куполом Брунеллески в центре Флоренции.', 'Famous cathedral with Brunelleschi''s dome in the heart of Florence.', 'Catedral famosa con la cúpula de Brunelleschi en el centro de Florencia.', 'Berühmter Dom mit Brunelleschis Kuppel im Herzen von Florenz.', 'достопримечательности', 43.7731, 11.2560, 'https://www.google.com/maps/search/?api=1&query=43.7731,11.2560', 'duomo|cathedral|catedral|dom', 10),
    ('uffizi-gallery', 'florence', 'Флоренция', 'Florence', 'Florencia', 'Florenz', 'Галерея Уффици', 'Uffizi Gallery', 'Galería Uffizi', 'Uffizien', 'Музей мирового искусства с работами Боттичелли, Леонардо и Микеланджело.', 'World-class museum with works by Botticelli, Leonardo and Michelangelo.', 'Museo de arte mundial con obras de Botticelli, Leonardo y Miguel Ángel.', 'Weltberühmtes Museum mit Werken von Botticelli, Leonardo und Michelangelo.', 'достопримечательности', 43.7678, 11.2553, 'https://www.google.com/maps/search/?api=1&query=43.7678,11.2553', 'uffizi|gallery|galeria|museum', 20),
    ('ponte-vecchio', 'florence', 'Флоренция', 'Florence', 'Florencia', 'Florenz', 'Понте-Веккьо', 'Ponte Vecchio', 'Ponte Vecchio', 'Ponte Vecchio', 'Средневековый мост через Арно с ювелирными лавками.', 'Medieval bridge over the Arno lined with jewellery shops.', 'Puente medieval sobre el Arno con joyerías.', 'Mittelalterliche Brücke über den Arno mit Juwelierläden.', 'достопримечательности', 43.7679, 11.2531, 'https://www.google.com/maps/search/?api=1&query=43.7679,11.2531', 'ponte|bridge|puente|brücke', 30),
    ('palazzo-vecchio', 'florence', 'Флоренция', 'Florence', 'Florencia', 'Florenz', 'Палаццо Веккьо', 'Palazzo Vecchio', 'Palazzo Vecchio', 'Palazzo Vecchio', 'Средневековый дворец на площади Синьории с башней и музеем.', 'Medieval palace on Piazza della Signoria with a tower and museum.', 'Palacio medieval en Piazza della Signoria con torre y museo.', 'Mittelalterlicher Palast an der Piazza della Signoria mit Turm und Museum.', 'достопримечательности', 43.7696, 11.2560, 'https://www.google.com/maps/search/?api=1&query=43.7696,11.2560', 'signoria|palace|palacio|palast', 40),
    ('accademia-florence', 'florence', 'Флоренция', 'Florence', 'Florencia', 'Florenz', 'Галерея Академии', 'Accademia Gallery', 'Galería de la Academia', 'Galleria dell''Accademia', 'Музей, где хранится знаменитая статуя Давида работы Микеланджело.', 'Museum home to Michelangelo''s famous David sculpture.', 'Museo que alberga el famoso David de Miguel Ángel.', 'Museum mit Michelangelos berühmter David-Statue.', 'достопримечательности', 43.7769, 11.2589, 'https://www.google.com/maps/search/?api=1&query=43.7769,11.2589', 'accademia|david|gallery|galeria', 50),

    ('milan-duomo', 'milan', 'Милан', 'Milan', 'Milán', 'Mailand', 'Миланский собор', 'Milan Cathedral', 'Duomo de Milán', 'Mailänder Dom', 'Готический собор на главной площади Милана с доступом на крышу.', 'Gothic cathedral on Milan''s main square with rooftop access.', 'Catedral gótica en la plaza principal de Milán con acceso a la azotea.', 'Gotischer Dom am Hauptplatz mit Zugang zum Dach.', 'достопримечательности', 45.4642, 9.1919, 'https://www.google.com/maps/search/?api=1&query=45.4642,9.1919', 'duomo|cathedral|catedral|dom', 10),
    ('sforza-castle', 'milan', 'Милан', 'Milan', 'Milán', 'Mailand', 'Замок Сфорца', 'Sforza Castle', 'Castillo Sforza', 'Castello Sforzesco', 'Замок и музейный комплекс рядом с парком Семпионе.', 'Castle and museum complex beside Sempione Park.', 'Castillo y complejo de museos junto al parque Sempione.', 'Burg- und Museumskomplex am Sempione-Park.', 'достопримечательности', 45.4707, 9.1796, 'https://www.google.com/maps/search/?api=1&query=45.4707,9.1796', 'sforza|castle|castillo|burg', 20),
    ('galleria-vittorio-emanuele', 'milan', 'Милан', 'Milan', 'Milán', 'Mailand', 'Галерея Виктора Эммануила II', 'Galleria Vittorio Emanuele II', 'Galería Vittorio Emanuele II', 'Galleria Vittorio Emanuele II', 'Историческая торговая галерея со стеклянным куполом у Дуомо.', 'Historic shopping arcade with a glass roof beside the Duomo.', 'Galería comercial histórica con techo de cristal junto al Duomo.', 'Historische Einkaufspassage mit Glasdach neben dem Dom.', 'достопримечательности', 45.4659, 9.1900, 'https://www.google.com/maps/search/?api=1&query=45.4659,9.1900', 'galleria|shopping|galeria|passage', 30),
    ('last-supper-milan', 'milan', 'Милан', 'Milan', 'Milán', 'Mailand', 'Тайная вечеря', 'The Last Supper', 'La Última Cena', 'Das Abendmahl', 'Фреска Леонардо да Винчи в трапезной монастыря Санта-Мария-делле-Грацие.', 'Leonardo da Vinci''s fresco in the refectory of Santa Maria delle Grazie.', 'Fresco de Leonardo da Vinci en Santa Maria delle Grazie.', 'Fresko von Leonardo da Vinci in Santa Maria delle Grazie.', 'достопримечательности', 45.4669, 9.1706, 'https://www.google.com/maps/search/?api=1&query=45.4669,9.1706', 'cenacolo|leonardo|fresco|fresko', 40),

    ('arena-verona', 'verona', 'Верона', 'Verona', 'Verona', 'Verona', 'Арена ди Верона', 'Verona Arena', 'Arena de Verona', 'Arena von Verona', 'Римский амфитеатр на площади Бра, где проходят оперные спектакли.', 'Roman amphitheatre on Piazza Bra, still used for opera performances.', 'Anfiteatro romano en Piazza Bra, aún utilizado para óperas.', 'Römisches Amphitheater an der Piazza Bra, heute noch für Opern genutzt.', 'достопримечательности', 45.4380, 10.9946, 'https://www.google.com/maps/search/?api=1&query=45.4380,10.9946', 'arena|amphitheatre|anfiteatro|amphitheater', 10),
    ('juliets-house', 'verona', 'Верона', 'Verona', 'Verona', 'Verona', 'Дом Джульетты', 'Juliet''s House', 'Casa de Julieta', 'Julias Haus', 'Исторический двор с балконом, связанный с легендой о Ромео и Джульетте.', 'Historic courtyard and balcony linked to the Romeo and Juliet legend.', 'Patio histórico y balcón ligados a la leyenda de Romeo y Julieta.', 'Historischer Hof und Balkon aus der Romeo-und-Julia-Legende.', 'достопримечательности', 45.4430, 10.9985, 'https://www.google.com/maps/search/?api=1&query=45.4430,10.9985', 'juliet|romeo|casa|haus', 20),
    ('piazza-erbe-verona', 'verona', 'Верона', 'Verona', 'Verona', 'Verona', 'Площадь Эрбе', 'Piazza delle Erbe', 'Piazza delle Erbe', 'Piazza delle Erbe', 'Живая площадь с рынком, кафе и историческими фасадами в центре Вероны.', 'Lively square with a market, cafés and historic façades in central Verona.', 'Plaza animada con mercado, cafés y fachadas históricas.', 'Lebendiger Platz mit Markt, Cafés und historischen Fassaden.', 'достопримечательности', 45.4431, 10.9977, 'https://www.google.com/maps/search/?api=1&query=45.4431,10.9977', 'piazza|market|mercado|markt', 30),
    ('castelvecchio-verona', 'verona', 'Верона', 'Verona', 'Verona', 'Verona', 'Кастельвеккьо', 'Castelvecchio', 'Castelvecchio', 'Castelvecchio', 'Средневековый замок и музей искусства рядом с мостом Скалигеров.', 'Medieval castle and art museum beside the Scaliger Bridge.', 'Castillo medieval y museo de arte junto al puente de los Scaligeri.', 'Mittelalterliche Burg und Kunstmuseum an der Scaligerbrücke.', 'достопримечательности', 45.4386, 10.9876, 'https://www.google.com/maps/search/?api=1&query=45.4386,10.9876', 'castle|museum|castillo|museum', 40),

    ('leaning-tower-pisa', 'pisa', 'Пиза', 'Pisa', 'Pisa', 'Pisa', 'Пизанская башня', 'Leaning Tower of Pisa', 'Torre inclinada de Pisa', 'Schiefer Turm von Pisa', 'Наклонная колокольня на площади Чудес.', 'Leaning bell tower on the Piazza dei Miracoli.', 'Campanario inclinado en la Piazza dei Miracoli.', 'Schiefer Glockenturm auf der Piazza dei Miracoli.', 'достопримечательности', 43.7230, 10.3966, 'https://www.google.com/maps/search/?api=1&query=43.7230,10.3966', 'tower|torre|turm|miracoli', 10),
    ('piazza-miracoli', 'pisa', 'Пиза', 'Pisa', 'Pisa', 'Pisa', 'Площадь Чудес', 'Piazza dei Miracoli', 'Plaza de los Milagros', 'Piazza dei Miracoli', 'Ансамбль собора, баптистерия и башни в зелёной исторической площади.', 'Ensemble of the cathedral, baptistery and tower on a historic green square.', 'Conjunto de catedral, baptisterio y torre en una plaza histórica.', 'Ensemble aus Dom, Baptisterium und Turm auf einer historischen Wiese.', 'достопримечательности', 43.7229, 10.3967, 'https://www.google.com/maps/search/?api=1&query=43.7229,10.3967', 'miracoli|square|plaza|platz', 20),
    ('baptistery-pisa', 'pisa', 'Пиза', 'Pisa', 'Pisa', 'Pisa', 'Баптистерий Пизы', 'Pisa Baptistery', 'Baptisterio de Pisa', 'Baptisterium von Pisa', 'Круглый романско-готический баптистерий рядом с Пизанской башней.', 'Round Romanesque-Gothic baptistery beside the Leaning Tower.', 'Baptisterio románico-gótico junto a la Torre de Pisa.', 'Rundes romanisch-gotisches Baptisterium neben dem Schiefen Turm.', 'достопримечательности', 43.7231, 10.3936, 'https://www.google.com/maps/search/?api=1&query=43.7231,10.3936', 'baptistery|baptisterio|baptisterium', 30),

    ('moscow-kremlin', 'moscow', 'Москва', 'Moscow', 'Moscú', 'Moskau', 'Московский Кремль', 'Moscow Kremlin', 'Kremlin de Moscú', 'Moskauer Kreml', 'Исторический кремлёвский комплекс с соборами, палатами и музеями.', 'Historic Kremlin complex with cathedrals, chambers and museums.', 'Complejo histórico del Kremlin con catedrales, palacios y museos.', 'Historischer Kremlkomplex mit Kathedralen, Palästen und Museen.', 'достопримечательности', 55.7520, 37.6175, 'https://www.google.com/maps/search/?api=1&query=55.7520,37.6175', 'kremlin|kreml|кремль|moskauer', 10),
    ('red-square-moscow', 'moscow', 'Москва', 'Moscow', 'Moscú', 'Moskau', 'Красная площадь', 'Red Square', 'Plaza Roja', 'Roter Platz', 'Главная площадь Москвы между Кремлём и ГУМом.', 'Moscow''s main square between the Kremlin and GUM department store.', 'Plaza principal de Moscú entre el Kremlin y los grandes almacenes GUM.', 'Moskaus Hauptplatz zwischen Kreml und Kaufhaus GUM.', 'достопримечательности', 55.7539, 37.6208, 'https://www.google.com/maps/search/?api=1&query=55.7539,37.6208', 'red square|plaza roja|roter platz|красная', 20),
    ('st-basils-cathedral', 'moscow', 'Москва', 'Moscow', 'Moscú', 'Moskau', 'Собор Василия Блаженного', 'St. Basil''s Cathedral', 'Catedral de San Basilio', 'Basilius-Kathedrale', 'Собор с разноцветными куполами на Красной площади.', 'Colourful-domed cathedral on Red Square.', 'Catedral de cúpulas coloridas en la Plaza Roja.', 'Kathedrale mit farbenfrohen Kuppeln am Roten Platz.', 'достопримечательности', 55.7525, 37.6231, 'https://www.google.com/maps/search/?api=1&query=55.7525,37.6231', 'st basil|vasily|basilio|basilius', 30),
    ('tretyakov-gallery', 'moscow', 'Москва', 'Moscow', 'Moscú', 'Moskau', 'Третьяковская галерея', 'Tretyakov Gallery', 'Galería Tretiakov', 'Tretjakow-Galerie', 'Главная коллекция русского искусства от икон до живописи XX века.', 'Leading collection of Russian art from icons to twentieth-century painting.', 'Gran colección de arte ruso, desde iconos hasta pintura del siglo XX.', 'Bedeutende Sammlung russischer Kunst von Ikonen bis zur Malerei des 20. Jahrhunderts.', 'достопримечательности', 55.7415, 37.6208, 'https://www.google.com/maps/search/?api=1&query=55.7415,37.6208', 'tretyakov|gallery|galeria|galerie', 40),
    ('gorky-park-moscow', 'moscow', 'Москва', 'Moscow', 'Moscú', 'Moskau', 'Парк Горького', 'Gorky Park', 'Parque Gorki', 'Gorki-Park', 'Большой городской парк на берегу Москвы-реки с набережной и павильонами.', 'Large riverside city park with a promenade and pavilions.', 'Gran parque junto al río con paseo y pabellones.', 'Großer Stadtpark am Fluss mit Promenade und Pavillons.', 'достопримечательности', 55.7298, 37.6038, 'https://www.google.com/maps/search/?api=1&query=55.7298,37.6038', 'gorky|park|parque|gorki', 50),

    ('brandenburg-gate', 'berlin', 'Берлин', 'Berlin', 'Berlín', 'Berlin', 'Бранденбургские ворота', 'Brandenburg Gate', 'Puerta de Brandeburgo', 'Brandenburger Tor', 'Неоклассические ворота и один из главных символов Берлина.', 'Neoclassical gate and one of Berlin''s best-known symbols.', 'Puerta neoclásica y uno de los símbolos más conocidos de Berlín.', 'Neoklassizistisches Tor und eines der bekanntesten Wahrzeichen Berlins.', 'достопримечательности', 52.5163, 13.3777, 'https://www.google.com/maps/search/?api=1&query=52.5163,13.3777', 'brandenburg|gate|puerta|tor', 10),
    ('reichstag-berlin', 'berlin', 'Берлин', 'Berlin', 'Berlín', 'Berlin', 'Рейхстаг', 'Reichstag Building', 'Edificio del Reichstag', 'Reichstagsgebäude', 'Здание парламента с современной стеклянной купольной смотровой площадкой.', 'Parliament building with a modern glass dome and viewing terrace.', 'Edificio del Parlamento con cúpula de cristal y mirador.', 'Parlamentsgebäude mit moderner Glaskuppel und Aussichtsterrasse.', 'достопримечательности', 52.5186, 13.3762, 'https://www.google.com/maps/search/?api=1&query=52.5186,13.3762', 'reichstag|parliament|parlamento|parlament', 20),
    ('museum-island-berlin', 'berlin', 'Берлин', 'Berlin', 'Berlín', 'Berlin', 'Музейный остров', 'Museum Island', 'Isla de los Museos', 'Museumsinsel', 'Остров на Шпрее с пятью знаменитыми музеями Берлина.', 'Spree island home to five of Berlin''s famous museums.', 'Isla del Spree con cinco museos famosos de Berlín.', 'Spreeinsel mit fünf berühmten Berliner Museen.', 'достопримечательности', 52.5169, 13.4010, 'https://www.google.com/maps/search/?api=1&query=52.5169,13.4010', 'museum island|museumsinsel|isla|museo', 30),
    ('berlin-wall-memorial', 'berlin', 'Берлин', 'Berlin', 'Berlín', 'Berlin', 'Мемориал Берлинской стены', 'Berlin Wall Memorial', 'Memorial del Muro de Berlín', 'Gedenkstätte Berliner Mauer', 'Мемориальный участок стены с сохранившимися фрагментами и музеем.', 'Memorial site with preserved wall sections and a museum.', 'Lugar conmemorativo con fragmentos conservados y museo.', 'Gedenkstätte mit erhaltenen Mauerteilen und Museum.', 'достопримечательности', 52.5351, 13.3904, 'https://www.google.com/maps/search/?api=1&query=52.5351,13.3904', 'wall|muro|mauer|memorial', 40),
    ('charlottenburg-palace', 'berlin', 'Берлин', 'Berlin', 'Berlín', 'Berlin', 'Дворец Шарлоттенбург', 'Charlottenburg Palace', 'Palacio de Charlottenburg', 'Schloss Charlottenburg', 'Барочный дворец с садами в западной части Берлина.', 'Baroque palace with gardens in western Berlin.', 'Palacio barroco con jardines en el oeste de Berlín.', 'Barockes Schloss mit Gärten im Westen Berlins.', 'достопримечательности', 52.5200, 13.2950, 'https://www.google.com/maps/search/?api=1&query=52.5200,13.2950', 'charlottenburg|palace|palacio|schloss', 50)
on conflict (id) do nothing;
